#!/usr/bin/env bash

# This is a 'deploy' action hook script. This script must be executable
# and will be run by the S2I process just before the original S2I 'run'
# script is run.
#
# This script is to allow a user to run any final steps
# just before the application is to be started. This can include running
# background tasks.

set -Eeuxo pipefail

# Dump out the set of environment variables which were used by the build.

echo " -----> Environment variables set for deploy script."

env

# Dump out the name of the current working directory.

echo " -----> Current working directory."

pwd


# Download and Install oc client

OC_TOOL_RELEASE="v3.11.0"
OC_TOOL_FILE_NAME="openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit"
OC_TOOL_BIN_DIR="${APP_ROOT}/oc-tool"

TMP_DIR=$( mktemp -d --suffix "oc-tool" )


pushd ${TMP_DIR}

echo " -----> Downloading OC Tool."

wget "https://github.com/openshift/origin/releases/download/${OC_TOOL_RELEASE}/${OC_TOOL_FILE_NAME}.tar.gz"
tar -xvf "${OC_TOOL_FILE_NAME}.tar.gz"

echo " -----> Installing OC Tool."

mkdir -p ${OC_TOOL_BIN_DIR}
mv ${OC_TOOL_FILE_NAME} ${OC_TOOL_BIN_DIR}

ln -s ${OC_TOOL_BIN_DIR}/*/oc ${APP_ROOT}/bin/oc

which oc

[[ $? -eq 0 ]] && echo " -----> OC Tool Installation finished successfully." \
               || echo " -----> OC Tool Installation failed."

popd

rm -rf ${TMP_DIR}
