#!/usr/bin/env bash

# This is a 'run' action hook script. This script must be
# executable and will be run by the S2I process as the last step after deployment.


set -Eeuxo pipefail


# Execute the flask application

if [ -z $S2I_SOURCE_PATH ]; then
    export S2I_SOURCE_PATH=$PWD
fi

export FLASK_APP="$S2I_SOURCE_PATH/app.py"


python -m flask run --host=$OSIRIS_HOST --port=$OSIRIS_PORT